# Text Style Transfer Evaluation Config
defaults:
  - base_eval
  - _self_
# Data
dataset: "???"
dataset_seed: null
base_path: "../data"
# Evaluation
prompt_0_to_1: ""
prompt_1_to_0: ""
# Reward
task_lm: "distilgpt2"
style_tokenizer: "bert-base-uncased"
lower_outputs: true
control_output_length: true