# Text Style Transfer Config
defaults:
  - base_tst
  - _self_
# Data
dataset: "yelp"
direction: "1_to_0"
# Reward
style_classifier_path: "./style_classifiers/yelp-bert-base-uncased-train"
lower_outputs: true
# Single Prompt Model
prompt_train_batch_size: 8
prompt_infer_batch_size: 16
# LM Adaptor Model
logit_bias: -10
# SQL Module
reward_shaping_old_min: 0
reward_shaping_old_max: 1
reward_shaping_new_min: -20
reward_shaping_new_max: 80
top_k: 50
# Trainer
save_dir: "./tst_test_outputs"
train_batch_size: 2
max_train_steps: 12000
train_shuffle: false
eval_batch_size: 16
eval_steps: 50
save_steps: 100
learning_rate: 5e-5
random_seed: 2

